zkopru-network/zkopru

package.json, packages/coordinator/src/coordinator.ts, packages/core/src/layer2.ts, packages/core/src/snark-verifier.ts, packages/core/src/zkopru-node.ts, packages/integration-test/package.json, packages/integration-test/tests/cases/context.ts, packages/integration-test/tests/index.test.ts, packages/prisma/package.json, packages/prisma/prisma/base.prisma, packages/prisma/prisma/postgres-migrator.prisma, packages/prisma/prisma/postgres.prisma, packages/prisma/prisma/sqlite-migrator.prisma, packages/prisma/prisma/sqlite.prisma, packages/prisma/src/index.ts, packages/tree/src/light-rollup-tree.ts, packages/tree/src/nullifier-tree.ts, packages/tree/tests/unit/nullifier-tree.test.ts, packages/utils/src/index.ts, packages/utils/src/worker.ts, yarn.lock
=> refactor: primsa transaction & scheduled jobs

packages/contracts/contracts/zkopru/storage/Reader.sol
Handle potential underflows in integration tests.
=> Better underflow handling

packages/contracts/contracts/consensus/BurnAuction.sol, packages/contracts/migrations/19_migration_dest.js
Add checks in consensus provider before allowing staking and bids.
=> Create separate auction for dest contract

.circleci/config.yml, jest.config.js, package.json, packages/contracts/test-cases/test/auction.soltest.js, packages/integration-test/package.json, packages/integration-test/tests/cases/context.ts, yarn.lock
Adds CI that builds and lints the project.
In the future we should run integration tests.
[See the latest build here](https://app.circleci.com/pipelines/github/JChanceHud/zkopru/63/workflows/a0e9a3fa-e2b5-4e61-a744-9f3ec0dfd907/jobs/64)
=> Add continuous integration

packages/contracts/migrations/2_poseidon.js, packages/contracts/package.json, packages/contracts/test-cases/migrations/2_poseidon.js, packages/contracts/truffle-config.js, packages/contracts/utils/poseidon-generator.js
Partially reverts the changes to the poseidon build system.
=> Poseidon revert

packages/circuits/src/pull-phase1.ts, packages/integration-test/tests/cases/context.ts
This fixes some simple issues preventing tests from running.
=> Test fixes

packages/cli/src/apps/coordinator/cli.ts, packages/cli/src/apps/coordinator/example-config/prompts/set-websocket.ts, packages/cli/src/apps/coordinator/parser.ts
Fixes a bug where the default cli values override the config values.
=> fix: defaults handling

packages/contracts/contracts/consensus/BurnAuction.sol
Adds comments to each function in the burn auction contract as suggested by Least Authority.
=> Add comments to burn auction

package.json, packages/contracts/contracts/consensus/BurnAuction.sol, packages/contracts/contracts/consensus/interfaces/IBurnAuction.sol, packages/contracts/src/abis/BurnAuction.ts, packages/contracts/src/abis/IBurnAuction.ts, packages/contracts/src/contracts/BurnAuction.d.ts, packages/contracts/src/contracts/IBurnAuction.d.ts, packages/contracts/test-cases/test/auction.soltest.js, yarn.lock
=> Auction bidding fix

CONTRIBUTING.md, packages/circuits/src/key-builder.ts, packages/cli/src/apps/coordinator/configurator/config-prompts/config-account.ts, packages/cli/src/apps/coordinator/configurator/config-prompts/save-config.ts, packages/cli/src/apps/wallet/configurator/menus/save-config.ts, packages/tree/src/light-rollup-tree.ts
Found some typos with the word "exising" instead of "existing" and also other typos in the CONTRIBUTING.md file.
=> fix: typo error in several places

packages/coordinator/src/client-api.ts, packages/core/src/context/layer2.ts
=> Return genesis block

packages/client/src/zkopru-node.ts, packages/database/src/schema.ts
Adds a db reset function for clearing client data in the browser wallet.
=> DB reset logic

packages/cli/src/apps/wallet/config.ts, packages/cli/src/apps/wallet/configurator/configurator.ts, packages/cli/src/apps/wallet/configurator/index.ts, packages/cli/src/apps/wallet/configurator/menus/load-node.ts, packages/cli/src/apps/wallet/parser.ts, packages/cli/src/apps/wallet/prompts/menus/account-detail-transfer-eth.ts, packages/cli/wallet.json, packages/client/src/zkopru-wallet.ts, packages/coordinator/src/auction-monitor.ts, packages/core/src/coordinator-manager.ts, packages/core/src/index.ts, packages/integration-test/tests/cases/context.ts, packages/integration-test/tests/index.test.ts, packages/utils/src/index.ts, packages/zk-wizard/src/zk-wallet-account.ts
Auto-selects a coordinator using the burn auction for submitting transactions and querying state info.
Closes zkopru-network/wallet#1
Related #216
=> Auto coordinator selection

packages/client/src/zkopru-node.ts, packages/coordinator/src/api.ts, packages/coordinator/src/coordinator.ts, packages/coordinator/src/middlewares/default/block-generator.ts, packages/coordinator/src/tx-pool.ts, packages/core/src/node/block-processor.ts, packages/database/src/connectors/indexed-db.ts, packages/database/src/schema.ts, packages/zk-wizard/src/zk-wallet-account.ts
Stores pending transactions on coordinator and client. Refactors tx forwarding and mempool.
Closes #216
Closes #210
=> Pending TX

packages/contracts/utils/testblock-generator.js
Decreases the gwei per byte fee in the testblock creation script to fix [this error](https://app.circleci.com/pipelines/github/sifnoc/zkopru/12/workflows/9574fb50-0841-4f6b-9415-8bc4af70d00e/jobs/104).
=> Fix testblock generation error in ci

packages/client/src/index.ts, packages/client/src/web.ts
Add some libraries to the exported client object (for web and node).
=> Client library exports

packages/cli/src/apps/coordinator/config.ts, packages/cli/src/apps/coordinator/example-config/prompts/set-websocket.ts, packages/cli/src/apps/wallet/config.ts, packages/cli/wallet.json, packages/client/package.json, packages/client/src/node.ts, packages/client/src/types.ts, packages/client/src/web.ts, packages/client/src/zkopru-node.ts, packages/client/src/zkopru-wallet.ts, packages/coordinator/src/tx-pool.ts, packages/core/src/node/block-processor.ts, packages/core/src/node/synchronizer.ts, packages/database/src/connectors/indexed-db.ts, packages/database/src/schema.ts, packages/database/src/schema.types.ts, packages/tree/src/utils/merkle-tree-sol.ts, packages/zk-wizard/src/zk-wallet-account.ts, yarn.lock
This PR adds a client method for retrieving transactions for a `ZkAddress`.
The client function `transactionsFor(zkAddress: string)` returns an object of the following structure:
```
{
pending: PendingTx[], // Only shows pending send transactions
sent: Tx[],
received: Tx[],
deposits: Deposit[],
withdrawals: Withdrawal[],
}
```
Schemas for these objects can be seen [here](https://github.com/zkopru-network/zkopru/blob/tx-client-info/packages/database/src/schema.ts#L209).
Each object in each array contains a `proposal` property that will exist if it has been included in an L2 block. It will include additional info like the L1 block number and unix timestamp.
Transactions will include an `amount` field and a `tokenAddress` field. If the token address is 0 the asset being sent is Ether.
Let me …
=> Transaction history client api

packages/circuits/tests/inclusion_proof.test.ts, packages/circuits/tests/zk_transaction_1_2.test.ts
Fix for an error on the integration test
=> fix: added missing treeCache for integration test

packages/contracts/test-cases/contracts/validator-testers/UtxoTreeValidatorTester.sol, packages/contracts/test-cases/test/validators/utxo-tree-validator.soltest.js
@JChanceHud 
https://github.com/zkopru-network/zkopru/blob/254134b40cd5a3eb859e101b6664b4e691f0d7d1/packages/contracts/contracts/zkopru/controllers/validators/UtxoTreeValidator.sol#L98-L114
as it seems the `appendSubTree` logic and its unit tests have no issues i was suspecting `getUTXO()` and wrote up a unit test for it. But it also worked as expected.
=> test: make sure onchain/offchain each provides same utxo items

.circleci/config.yml, packages/account/src/viewer.ts, packages/client/package.json, packages/contracts/contracts/zkopru/controllers/UserInteractable.sol, packages/coordinator/src/api.ts, packages/coordinator/src/tx-pool.ts, packages/core/src/node/block-processor.ts, packages/core/src/node/zkopru-node.ts, packages/database/scripts/generateTypes.ts, packages/database/src/connectors/indexed-db.ts, packages/database/src/schema.ts, packages/database/src/schema.types.ts, packages/transaction/src/index.ts, packages/transaction/src/memo.ts, packages/transaction/src/tx-builder.ts, packages/transaction/src/zk-tx.ts, packages/utils/package.json, packages/utils/src/eip712.ts, packages/utils/src/index.ts, packages/utils/tests/unit/index.test.ts, packages/zk-wizard/package.json, packages/zk-wizard/src/zk-wallet-account.ts, packages/zk-wizard/src/zk-wizard.ts, yarn.lock
Adds support for including a withdrawal prepay authorization in a memo.
Switches V2 memo abi signature to use mostly zero values to save gas.
Closes #274
=> Instant withdraw info memo

dockerfiles/Circuits.dockerfile, dockerfiles/Circuits.light.dockerfile, dockerfiles/Cli.dockerfile, dockerfiles/Contract.dockerfile, dockerfiles/Contract.integration.dockerfile, dockerfiles/Coordinator.dockerfile, dockerfiles/Playground.dockerfile, dockerfiles/PostgresSetup.dockerfile
Closes #304 
Switches all Docker images to NodeJS 16
=> fix: use python2 package in alpine based images

packages/database/src/connectors/indexed-db.ts, packages/database/src/schema.ts
Support indexes for queries that use arrays of values in the where clause.
Adds a new index supporting the nullifier tree.
=> Indexed db index support

packages/core/src/context/layer2.ts, packages/core/src/node/block-processor.ts
Fixes synchronization when #333 happens
=> fix: check for an existing slash

packages/core/src/node/synchronizer.ts, packages/database/src/block-cache.ts
=> feat: load events by scanning, then use subscription

.circleci/config.yml, packages/coordinator/src/middlewares/default/block-generator.ts, packages/core/src/context/layer2.ts
Fix coordinator error handling on Issue #364
=> fix coordinator error handling

compose/docker-compose.dev.yml, compose/docker-compose.instant-block.yml, packages/cli/coordinator.dev.json
in order to run local coordinator by `yarn develop`
=> fix: docker compose files

packages/integration-test/tests/cases/6-2_zk_tx_round_1-2.ts, packages/integration-test/tests/cases/7_zk_tx_round_2.ts, packages/integration-test/tests/index.test.ts
Added swap test case for integration test.
=> [chore] add swap test cases

packages/dataset/src/testset-txs.ts, packages/dataset/src/testset-utxos.ts, packages/transaction/src/tx-builder.ts, packages/utils/src/index.ts, packages/zk-wizard/tests/unit/index.test.ts
This PR update tx size calculation for memoV2 but does not include calculation with prepayInfo.
close #377
=> [chore] fix tx size calculation for memoV2

packages/coordinator/src/auction-monitor.ts
Fix issue #379 
- set bid 20% higher amount than previous, due to many bid transactions in competition.\
- use pending balance for bidding
Note that we need to reduce `maxBid` amount in the default config in test.
Current, `maxBid` is 20000 gwei. And the minimum bid amount is 10000 gwei. 
That means the `maxBid` will be reaching after eight times bidding ( 1.1**8 == 2.14...) in competition.
=> Fix auction bid amount
