zkopru-network/zkopru

packages/contracts/contracts/consensus/BurnAuction.sol
packages/contracts/src/abis/BurnAuction.ts
packages/contracts/src/contracts/BurnAuction.d.ts

Adds underflow protection for the `roundForBlock` function as a safety measure.
Also makes the `zkopru` address in the burn auction public.

More underflow protection

---

tsconfig.json

Using the sqlite database is broken because of issues calling static methods on classes in Typescript. This change fixes these issues.
[More info here](https://stackoverflow.com/questions/50203369/class-constructor-cannot-be-invoked-without-new-typescript-with-commonjs/50203532#50203532).
Specifically this issue is occurring [here where an async class method is being invoked](https://github.com/zkopru-network/zkopru/blob/develop/packages/cli/src/apps/coordinator/configurator/config-prompts/load-database.ts#L62). 
If ES5 is needed for downstream projects it may be possible to work around this, though downstream projects could simply use shims.

Compile to es6

---

packages/contracts/src/layer1.ts
packages/contracts/utils/ts-generator.js

This pr fixes the contract leaks by instantiating each `Contract` object without a provider and then setting it after. This avoids the root cause of the problem which is in the `Eth` initialization of the Contract object.
Temporary fix until ChainSafe/web3.js#3866 lands.
Fixes #135

Fix contract leaks

---

packages/cli/src/apps/coordinator/cli.ts
packages/cli/src/apps/coordinator/example-config/index.ts
packages/cli/src/apps/coordinator/example-config/menu.ts
packages/cli/src/apps/coordinator/example-config/prompts/create-wallet.ts
packages/cli/src/apps/coordinator/example-config/prompts/output-path.ts
packages/cli/src/apps/coordinator/example-config/prompts/set-db.ts
packages/cli/src/apps/coordinator/example-config/prompts/set-public-url.ts
packages/cli/src/apps/coordinator/example-config/prompts/set-websocket.ts
packages/coordinator/src/auction-monitor.ts
packages/utils/src/index.ts

This PR makes the `--generateConfig` flag interactive. Ideally a coordinator operator would simply do the following:
```sh
$ zkopru --generateConfig
$ zkopru --config ./config.json --daemon
```
Output of the above
`custom-config.json`:
```json
{
"address": "0xF4A46BEA80d0D21a11306DDE6cb0fFA91fF95ADd",
"bootstrap": true,
"websocket": "ws://192.168.1.199:9546",
"maxBytes": 131072,
"priceMultiplier": 48,
"port": 8888,
"maxBid": 20000,
"daemon": false,
"publicUrls": "my-url.domain.com:8888,127.0.0.1:8888",
"keystore": {
"version": 3,
"id": "f28c77b3-93de-4573-80d6-6efb51bf14a0",
"address": "a8a25c573060ce39ade23af46893686c46f2e7cc",
"crypto": {
"ciphertext": "58136576004760d5247f025d33ba5b76d6667972acbc8997351e305c24205079",
"cipherparams": {
"iv": "d7050691001729962f6240d4501d2dcb"
}, …
```

Interactive config creation

---

packages/contracts/migrations/16_zk_optimistic_rollup.js
packages/contracts/migrations/4_ui.js
packages/contracts/migrations/6_utxo_tree_validator.js

Closes #182 
Working on deploying a new set of contracts to the Goerli testnet. Semi-blocked by the berlin hardfork and [this issue](https://github.com/trufflesuite/truffle/issues/3935), currently updating my local node to use `--rpc.allow-unprotected-txs` for deployment.

Ensure poseidon contracts exist for linking

---

packages/contracts/src/tx-util.ts
packages/coordinator/tests/unit/coordinator.test.ts
packages/integration-test/tests/index.test.ts

Uses the default web3 nonce handling instead of counting pending transactions ourselves.
Closes #189

Fix nonce race condition

---

packages/core/src/node/block-processor.ts
packages/core/src/node/zkopru-node.ts
packages/database/src/connectors/indexed-db.ts
packages/database/src/schema.ts
packages/database/src/types.ts

Accelerates simple queries in IndexedDB when possible. Reduces block synchronization time for current test chain in browser from `23 minutes` to `1 minute 20 seconds`. This is comparable to sqlite sync performance in cli.
Adds compound index syntax to schema definition. Index support in IndexedDB version bumps.

Indexed db performance

---

packages/contracts/test-cases/test/libraries/utxo-tree.soltest.js
packages/core/src/node/block-processor.ts
packages/database/README.md
packages/database/src/connectors/indexed-db.ts
packages/database/src/connectors/postgres.ts
packages/database/src/connectors/sqlite-memory.ts
packages/database/src/connectors/sqlite.ts
packages/database/src/preset.ts
packages/database/src/types.ts
packages/database/tests/database/transaction.ts
packages/dataset/src/testset-zktxs.ts
packages/integration-test/tests/index.test.ts
packages/tree/src/grove.ts
packages/tree/src/light-rollup-tree.ts
packages/tree/src/nullifier-tree.ts
packages/tree/tests/unit/grove.test.ts
packages/tree/tests/unit/nullifier-tree.test.ts
packages/tree/tests/unit/utxo-tree.test.ts
packages/tree/tests/unit/withdrawal-tree.test.ts
packages/utils/src/index.ts
packages/zk-wizard/tests/unit/index.test.ts

Performs block processing operations in a single database transaction so a power failure or abnormal exit condition will not corrupt the database.
Closes #222 
Refactors some tree operations to accept a `TransactionDB`. This lets them be a part of a larger transaction. The downside is when they are used independently the call has to be manually wrapped in a db transaction. I thought about making the `TransactionDB` argument optional (and auto-generate a transaction when needed) but decided it was unnecessary.
This also adds an optional in-memory cache to the tree. This is necessary because a transaction doesn't modify the database until it is committed but some operations expect the changes to be in the database. I've implemented it as an in-memory cache that is cleared when the …

Atomic sync

---

.circleci/config.yml
packages/cli/src/apps/coordinator/configurator/config-prompts/load-database.ts
packages/cli/src/apps/coordinator/configurator/configurator.ts
packages/contracts/utils/testblock-generator.js
packages/core/src/node/block-processor.ts
packages/core/src/node/full-node/index.ts
packages/core/src/node/light-node/index.ts
packages/core/src/node/synchronizer.ts
packages/core/src/node/zkopru-node.ts
packages/database/README.md
packages/database/src/block-cache.ts
packages/database/src/connectors/indexed-db.ts
packages/database/src/connectors/postgres.ts
packages/database/src/connectors/sqlite-memory.ts
packages/database/src/connectors/sqlite.ts
packages/database/src/helpers/memory.ts
packages/database/src/helpers/shared.ts
packages/database/src/helpers/sql.ts
packages/database/src/index.ts
packages/database/tests/database/find.ts
packages/integration-test/tests/index.test.ts

A more simple implementation to replace #233 
This implementation quarantines proposals, deposits, finalization, and anything else that happens on chain in an in-memory cache. During this quarantine time (15-30 blocks) the data is not written to the DB. The cache can expose some information about the quarantined data (e.g. pending balances, deposits, withdrawals, etc.). Once sufficient time passes the data is written to disk automatically.
This is a more simple approach. It does not allow the user to optimistically interact with funds but is more likely to work well.
Coordinators can run a node with a lower `BLOCK_CONFIRMATIONS` value to reduce the time before a block is generated (to avoid wasting the rounds they own). It might make sense to allow the user to adjust this value in the …

Reorg revert handling

---

packages/account/src/account.ts
packages/account/src/hdwallet.ts
packages/account/tests/account.test.ts
packages/babyjubjub/src/point.ts
packages/client/tests/rpc.test.ts
packages/contracts/test-cases/test/libraries/utxo-tree.soltest.js
packages/coordinator/tests/unit/coordinator.test.ts
packages/core/src/node/block-processor.ts
packages/core/src/validator/validator.ts
packages/database/src/block-cache.ts
packages/database/src/connectors/indexed-db.ts
packages/database/src/connectors/postgres.ts
packages/database/src/connectors/sqlite-memory.ts
packages/database/src/connectors/sqlite.ts
packages/database/src/helpers/callbacks.ts
packages/database/src/preset.ts
packages/database/src/types.ts
packages/database/tests/database/transaction.ts
packages/dataset/src/testset-predefined.ts
packages/integration-test/tests/cases/6_zk_tx_round_1.ts
packages/integration-test/tests/cases/7_zk_tx_round_2.ts
packages/integration-test/tests/cases/9_zk_tx_round_3.ts
packages/tree/src/grove.ts
packages/tree/src/light-rollup-tree.ts
packages/tree/src/nullifier-tree.ts
packages/tree/tests/unit/grove.test.ts
packages/utils/src/index.ts

Refactors transaction history calculation logic.
Uses multi tx endpoint for integration test round 3 transactions.
Fixes a race condition in light rollup tree `getStartingLeafProof` (fixes intermittent withdrawal problem).
Adds revert logic for rollup tree state variables.
Adds merkle proof test against external SMT implementation.
Change hexify, reject hexadecimal string without `0x` prefix.
async db tx callback support
Includes #266 
Closes #268

TX history refactor/hexify fixes/tree fixes

---

packages/core/src/node/block-processor.ts
packages/database/src/index.ts
packages/database/src/preset.ts
packages/integration-test/package.json
packages/integration-test/tests/cases/context.ts
packages/tree/src/grove.ts
packages/tree/src/index.ts
packages/tree/src/light-rollup-tree.ts
packages/tree/src/nullifier-tree.ts
packages/tree/src/sample.ts
packages/tree/src/utils/index.ts
packages/tree/src/utils/tree-cache.ts
packages/tree/src/utxo-tree.ts
packages/tree/src/withdrawal-tree.ts
packages/tree/tests/unit/grove.test.ts
packages/tree/tests/unit/light-rollup-tree-test.ts
packages/tree/tests/unit/nullifier-tree.test.ts
packages/tree/tests/unit/withdrawal-tree.test.ts

The global tree cache is causing multiple nodes in a single process to modify each others data. This is fixed by creating tree cache instances for each grove instance.
Moves tree cache from `database` package to `tree` package.
Closes #271

Fix global tree cache

---

packages/coordinator/src/tx-pool.ts

`data` should be [outflow public data](https://github.com/zkopru-network/zkopru/blob/develop/packages/transaction/src/zk-tx.ts#L20). Strings need to be converted to `BN/Fp` number types.
Closes #276

Pending transaction crash fix

---

packages/tree/src/light-rollup-tree.ts

Disables writing a new start point to the database for the light rollup tree. No `TreeNode` entries are deleted so all indexes should be accessible regardless of current index.
Closes #279

Fix rollup out of range issue

---

packages/client/src/zkopru-wallet.ts
packages/core/src/node/block-processor.ts
packages/core/src/node/synchronizer.ts
packages/core/src/node/zkopru-node.ts
packages/database/src/schema.ts
packages/database/src/schema.types.ts

Improved transaction history calculation. The original implementation worked but because of the nullifier bug I refactored to a broken version. This PR puts back the logic of "if we know the nullifiers before processing the block we're the sender".
Refactors how amounts are stored to use both `erc20Amount` and `eth`.

TX history

---

packages/database/src/helpers/memory.ts
packages/database/tests/database/find.ts

Fixes a bug that caused the `ne` operator to fail to work with `null` values. e.g. documents with non-null fields would be returned.

fix: proper null handling in ne expressions for indexeddb

---

README.md
packages/account/src/viewer.ts
packages/client/src/zkopru-wallet.ts
packages/core/src/node/block-processor.ts
packages/core/src/node/synchronizer.ts
packages/database/src/connectors/indexed-db.ts
packages/database/src/schema.ts
packages/dataset/package.json
packages/dataset/tests/index.test.ts
packages/transaction/src/utxo.ts
packages/zk-wizard/src/zk-wallet-account.ts

Create a table called `PendingDeposit` that stores short lived references to utxo notes for a deposit. The client can access these immediately (e.g. before the deposit transaction is confirmed and events are emitted).
Fix the transaction fee stored on `Withdrawal` entries.
Fix a bug preventing withdrawals from being stored without a prepay signature.
Change the `PendingTx` schema to match that of `Tx`.

Pending support

---

.drone.yml

drone CI is supported [downstream build](http://plugins.drone.io/drone-plugins/drone-downstream/) as a plugin(=image)
this config only has a trigger for starting [stress-test](https://github.com/zkopru-network/stress-test) testing pipeline when zkopru main branch updated.

drone CI config

---

packages/zk-wizard/src/zk-wallet-account.ts

Change `ZkWalletAccount#sendTx()` to return zkTx hash
In order for client applications to track transactions which users made in the apps has been included or not.

chore: layer2 sendTx returns zkTx hash

---

packages/client/src/zkopru-node.ts
packages/core/src/node/synchronizer.ts
packages/zk-wizard/src/zk-wizard.ts

Use the Zkopru IPFS gateway by default. Allows a client to pass a custom gateway url.
Fixes a bug with web3 provider connection detection.

Ipfs gateway fix

---

packages/coordinator/src/middlewares/default/block-proposer.ts
packages/core/src/context/layer2.ts
packages/core/src/node/full-node/fullnode-validator.ts
packages/database/src/schema.ts
packages/utils/src/index.ts

Adds an index to the tree node database collection to improve sync performance.
Increases the gas allowance when proposing blocks.
Verifies deposit commit hashes before including them in an L2 block.

Propose fixes

---

packages/client/src/zkopru-wallet.ts
packages/client/tests/rpc.test.ts
packages/core/src/context/layer2.ts
packages/core/src/node/synchronizer.ts
packages/core/src/validator/offchain/offchain-tx-validator.ts
packages/database/src/connectors/indexed-db.ts
packages/database/src/helpers/memory.ts
packages/database/src/helpers/shared.ts
packages/database/src/helpers/sql.ts
packages/database/src/schema.ts
packages/database/src/types.ts
packages/database/tests/indexed-db.test.ts
packages/database/tests/test-schema.ts

Uses indexes in scan operations for the indexeddb connector.
This may make #342 unnecessary, a few more queries can be optimized to take hundreds of milliseconds off each block processing time. This would let us avoid downloading, decompressing, and ingesting the state tree from another node.
Time to sync first 200 blocks: 6 minutes 16 seconds
Previous time to sync first 200 blocks: 17 minutes 40 seconds

Index perf

---

packages/client/src/zkopru-wallet.ts
packages/zk-wizard/src/zk-wallet-account.ts

Currently, ZkWalletAccount has unresolved promise inside its constructor and it's cumbersome to manually wait them resolved outside. For example, the code using ZkWalletAccount has to be check the if the promise returned by `this.node.tracker.addAccounts(account)` resolved or not by checking length of `tracker.transferTrackers` doing something similar to following code.
```ts
const wallet = new ZkWalletAccount(config)
await new Promise((resolve) => {
// polling to check the transferTrackers length
setInterval(() => {
if (wallet.node.tracker.transferTrackers === 1)  {
clearInterval(); resolve()
}, 500)
})
// now wallet is initialized properly.
```
Instead of doing this, implement async constructor and wait it initialized. and this can be used like this
```ts
const wallet = await …
```

[fix] add async constructor to zk-wallet and zk-wallet-account

---

packages/client/src/types.ts
packages/client/src/zkopru-node.ts
packages/database/src/connectors/indexed-db.ts

Currently, only one database file, the name 'zkopru', for using zkopru web wallet.
We need databases for each network and each zkopru contract in indexedDB.
To be like this
related branch [wallet - feat/network-selector](https://github.com/sifnoc/wallet/tree/feat/network-selector)

create database file with name by each network or contract

---

packages/utils/src/worker.ts
packages/zk-wizard/tests/unit/index.test.ts

the worker in block-processor cannot stop immediately when `stop()`
#392

fix worker stop first

---

dockerfiles/Cli.dockerfile
dockerfiles/Coordinator.dockerfile
dockerfiles/Playground.dockerfile

Based on the new alpine release, the package repo deprecates python2. Therefore we need to specify specific repository version in docker file when installing python2 by `apk add python2`.
In addition to that, go get seems not working without env of `GO111MODULE=off`.
https://alpinelinux.org/posts/Alpine-3.16.0-released.html

Fix docker compose for alpine release v3.16

---

packages/client/src/node.ts
packages/client/src/types.ts
packages/client/src/zkopru-node.ts

- Fixes an issue where creating a node by using `Zkopru.Node()` (from `@zkopru/client`) was not tracking UTXOs for the accounts. The `accounts` argument was not being passed when `FullNode` instance created.
- Add option to specify database name when creating a Node.
- Export `ZkopruNode` and `ZkopruWallet` from client package.
Note: Had to skip the tests for now as it times out on connection to docker (`core/tests`). Need to investigate/fix this separately.

Minor fixes/improvements in client package

---

packages/client/src/node.ts
packages/core/src/node/synchronizer.ts

I think I have found an issue in the UtxoDeposit listener function in the [synchronizer](https://github.com/zkopru-network/zkopru/blob/57ceb6a8f1b0f4d75feb451cc7fe935a76e14b5c/packages/core/src/node/synchronizer.ts).
In the `listenDepositUtxos` function, while processing the [existing blocks](https://github.com/zkopru-network/zkopru/blob/57ceb6a8f1b0f4d75feb451cc7fe935a76e14b5c/packages/core/src/node/synchronizer.ts#L646), if the owner of a `DepositUtxo` event is not one of the `addresses` being tracked, it exits the function (`return` statement). This prevent processing of all further events and blocks. 
Moreover it prevents the [code for attaching a subscriber](https://github.com/zkopru-network/zkopru/blob/57ceb6a8f1b0f4d75feb451cc7fe935a76e14b5c/packages/core/src/node/synchronizer.ts#L6 …

Fix in UtxoDeposit listener
